server:
  port: 9000

spring:
  profiles:
    active: test

  jpa:
    show-sql: true
    generate-ddl: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        show-sql: true
        SQL: trace
        format_sql: true
        use_sql_comments: true
        type:
          descriptor:
            sql: trace
        jdbc:
          batch_size: 5
        default_batch_fetch_size: 1000

  sql:
    init:
      mode: always

  data:
    redis:
      host: localhost
      port: 6379

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testdb
    username: sa
    password:

  h2:
    console:
      enabled: true
      path: /h2

logging:
  level:
    org:
      hibernate:
        type: trace
